In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arrSlice = arr[0:6]
arrSlice

array([0, 1, 2, 3, 4, 5])

In [7]:
arrSlice[:] = 0
arrSlice

array([0, 0, 0, 0, 0, 0])

In [8]:
arr #Well... damn it

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [12]:
arrCopy = arr.copy() #Aahh, our savior!
arrCopy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [13]:
arrCopy[:] = 25
arrCopy

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [14]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])