In [2]:
import numpy as np

In [3]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((5, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.61090147, 0.87542763, 0.54085058, 0.40090126, 0.52567678])

In [13]:
np.random.rand(4, 4)

array([[0.34346988, 0.84188024, 0.21684455, 0.02314938],
       [0.62815015, 0.73691595, 0.07328358, 0.81486035],
       [0.22159594, 0.36525512, 0.37016747, 0.35369504],
       [0.15727075, 0.1648257 , 0.27303079, 0.85048957]])

In [16]:
np.random.randint(3, 28)

25

In [17]:
np.random.randint(3, 28, (5, 5))

array([[25, 25, 23, 19,  3],
       [ 9,  5, 22, 17, 18],
       [11, 25, 16, 21, 23],
       [11,  4, 23,  6,  3],
       [22, 26, 25, 25, 26]])