In [61]:
import numpy as np

In [62]:
arr = np.random.randint(1, 20, 10)
arr

array([12, 12,  7,  9, 18, 15, 14, 13, 13, 16])

In [63]:
matrix = np.reshape(arr, (2,5), 'C')
matrix

array([[12, 12,  7,  9, 18],
       [15, 14, 13, 13, 16]])

In [64]:
arr.max()

18

In [65]:
matrix.max()

18

In [66]:
matrix.max(1) #Search through rows (1)

array([18, 16])

In [67]:
matrix.max(0) #Search through columns (0)

array([15, 14, 13, 13, 18])

In [68]:
arr.argmax()

4

In [69]:
matrix.argmax()

4

In [70]:
matrix.argmax(1)

array([4, 4])

In [71]:
matrix.argmax(0)

array([1, 1, 1, 1, 0])

In [72]:
arr.min()

7

In [73]:
matrix.min()

7

In [74]:
matrix.min(0)

array([12, 12,  7,  9, 16])

In [75]:
matrix.min(1)

array([ 7, 13])

In [76]:
arr.argmin()

2

In [77]:
matrix.argmin()

2

In [78]:
matrix.argmin(0)

array([0, 0, 0, 0, 1])

In [79]:
matrix.argmin(1)

array([2, 2])

In [80]:
arr

array([12, 12,  7,  9, 18, 15, 14, 13, 13, 16])

In [81]:
arr.ptp() #distance between max and min

11

In [82]:
matrix.ptp()

11

In [83]:
matrix.ptp(1)

array([11,  3])

In [84]:
matrix.ptp(0)

array([3, 2, 6, 4, 2])

In [85]:
np.percentile(arr, 50)

13.0

In [86]:
arr.sort()
arr

array([ 7,  9, 12, 12, 13, 13, 14, 15, 16, 18])

In [87]:
np.median(arr)

13.0

In [88]:
np.median(matrix, 0)

array([10. , 11.5, 13.5, 14. , 15.5])

In [89]:
np.median(matrix, 1)

array([12., 15.])

In [90]:
np.std(arr)

3.047950130825634

In [91]:
np.var(arr)

9.290000000000001

In [92]:
np.std(arr) ** 2

9.29

In [93]:
np.mean(arr)

12.9

In [94]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

In [95]:
b = np.expand_dims(b, axis=0) #We need to expand our array

In [96]:
np.concatenate((a, b)) #dims must be equal

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
np.concatenate((a, b.T), axis=1) #dims must be equal

array([[1, 2, 5],
       [3, 4, 6]])