In [1]:
import numpy as np

In [3]:
scalar = np.array(54)
scalar.ndim

0

In [4]:
vector = np.array([1, 2, 3])
vector.ndim

1

In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrix.ndim

2

In [10]:
tensor = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


3

Changing array dimensions

In [11]:
vector1 = np.array([1, 2, 3], ndmin=4)
print(vector1)
vector1.ndim

[[[[1 2 3]]]]


4

In [12]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [14]:
squeeze = np.squeeze(vector1)
print(squeeze)
squeeze.ndim

[1 2 3]


1