In [1]:
import numpy as np

In [3]:
arr = np.linspace(1, 10, 10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [6]:
cond_index = arr > 5

In [9]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [14]:
arr[arr % 2 == 0] = 0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0], dtype=int8)

In [16]:
arr[arr == 0] = 1
arr

array([1, 1, 3, 1, 5, 1, 7, 1, 9, 1], dtype=int8)