In [3]:
import numpy as np

In [2]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
# unidimensional array aka vector
arr =  np.array(list)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# bidimensional array aka matrix
matrix = np.array(list2)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# accessing vector elements by index
print(arr[3])
print(arr[3] + arr[5])

4
10


In [14]:
# accessing matirx elements by index [rows, columns]
matrix[1, 2]

6

In [21]:
# slicing a vector
print(arr[3:7])

print(arr[:5])

print(arr[2:])

print(arr[::2])

[4 5 6 7]
[1 2 3 4 5]
[3 4 5 6 7 8 9]
[1 3 5 7 9]


In [22]:
print(arr[-4:])

[6 7 8 9]


In [26]:
# slicing a matrix [srow:erow:strow, scolumn, ecolumn, stcolumn] -> where s = start ; e = end ; st = step
matrix[1:, 0:2]

array([[4, 5],
       [7, 8]])

In [29]:
list3 = [
    [[0, 1], [2, 3]],
    [[4, 5], [6, 7]],
    [[8, 9], [10, 11]]   
]

# multidimensional array aka tensor
tensor = np.array(list3)
tensor

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [34]:
# slicing a matrix [srow:erow:strow, scolumn, ecolumn, stcolumn] -> where s = start ; e = end ; st = step
tensor[1:2, ::2]

array([[[4, 5]]])