In [1]:
import numpy as np

In [2]:
list = [1, 2]
list

[1, 2]

In [3]:
list * 2

[1, 2, 1, 2]

In [4]:
arr = np.arange(0, 10)

In [7]:
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr2 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
1 / arr2

/tmp/ipykernel_17449/3854864060.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
arr2 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
arr + (arr2 + 1)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
matrix = arr.reshape(2, 5)
matrix2 = matrix.copy()

In [16]:
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
matrix + matrix2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [19]:
np.matmul(matrix, matrix2.T)

array([[ 30,  80],
       [ 80, 255]])

In [20]:
matrix @ matrix2.T

array([[ 30,  80],
       [ 80, 255]])