In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 10, (3, 2))

In [3]:
arr.shape

(3, 2)

In [4]:
arr

array([[6, 5],
       [3, 9],
       [2, 1]])

In [6]:
arr.reshape(1, 6)

array([[6, 5, 3, 9, 2, 1]])

In [8]:
arr.reshape(6, 1)

array([[6],
       [5],
       [3],
       [9],
       [2],
       [1]])

In [9]:
arr.reshape(2, 3)

array([[6, 5, 3],
       [9, 2, 1]])

In [10]:
np.reshape(arr, (2, 3), 'C') #C style (Search by rows)

array([[6, 5, 3],
       [9, 2, 1]])

In [11]:
np.reshape(arr, (2, 3), 'F') #Fortran style (Search by columns)

array([[6, 2, 9],
       [3, 5, 1]])

In [12]:
np.reshape(arr, (2, 3), 'A') #Local machine optimisation 

array([[6, 5, 3],
       [9, 2, 1]])