In [1]:
import numpy as np

In [58]:
escalar = 12
vector = np.array([1,2,3])
matrix = np.array([
    [1,2],
    [3,4],
    [5,6]
])
tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
    [[31,32,33],[34,35,36],[37,38,39]]
])

In [14]:
print(matrix)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
matrix_t=matrix.T

print(matrix_t)

[[1 3 5]
 [2 4 6]]


In [16]:
print(vector)

[1 2 3]


In [18]:
vector_t=vector.T

print(vector_t)

[1 2 3]


In [19]:
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]

 [[31 32 33]
  [34 35 36]
  [37 38 39]]]


In [20]:
tensor_t = tensor.T

print(tensor_t)

[[[ 1 11 21 31]
  [ 4 14 24 34]
  [ 7 17 27 37]]

 [[ 2 12 22 32]
  [ 5 15 25 35]
  [ 8 18 28 38]]

 [[ 3 13 23 33]
  [ 6 16 26 36]
  [ 9 19 29 39]]]


In [23]:
matrix_2 = np.array([
    [7,8],
    [9,10],
    [11,12]
])

In [52]:
C = matrix + matrix_2

print(C)

[[ 8 10]
 [12 14]
 [16 18]]


In [48]:
def matrixSum(A,B): # Matrix addition using .shape
    for i in range(0,A.shape[0]):
        for j in range(0,A.shape[1]):
            C[i][j]=A[i][j]+B[i][j]
    
    return C

In [49]:
matsum = matrixSum(matrix,matrix_2)

print(matsum)

[[ 8 10]
 [12 14]
 [16 18]]


In [50]:
def matrixSum(A,B): # Matrix addition using len()
    for i in range(0,len(A)):
        for j in range(0,len(A.T)):
            C[i][j]=A[i][j]+B[i][j]
    
    return C

In [51]:
matsum_2 = matrixSum(matrix,matrix_2)

print(matsum_2)

[[ 8 10]
 [12 14]
 [16 18]]


In [56]:
def matrixAddScalar(A,B): # Where A is a Matrix and B an scalar
    for i in range(0,len(A)):
         for j in range(0,len(A.T)):
            C[i][j]=A[i][j]+B
    
    return C

In [59]:
matnscalar = matrixAddScalar(matrix,escalar)

print(matnscalar)

[[13 14]
 [15 16]
 [17 18]]
