In [27]:
import numpy as np

escalar = 12
vector = np.array([8,15,9])
matrix = np.array([
    [1,2],
    [3,4],
    [5,6]
])

In [21]:
def myBroadcasting(A,B): 
    
    C = np.zeros((A.shape[0],A.shape[1]), dtype=int)
    
    for i in range(0,A.shape[0]):
        for j in range(0,A.shape[1]):
            C[i][j]=A[i][j]+B[j]
    
    return C

In [28]:
sumMat = myBroadcasting(matrix.T,vector)

print(sumMat)

[[ 9 18 14]
 [10 19 15]]


In [35]:
broadMat = vector + escalar

print(broadMat)

[20 27 21]
