In [10]:
import numpy as np

escalar = 12
vector = np.array([8,15])
matrix = np.array([
    [1,2],
    [3,4],
    [5,6]
])

matrix_2 = np.array([
    [7,8],
    [9,10],
    [11,12]
])

In [84]:
A = matrix * vector

B = matrix.dot(matrix_2.T)

print(A)
print(B)

[[ 8 30]
 [24 60]
 [40 90]]
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]]


In [72]:
def myDot(A,B):
# Where A is a matrix with m_A rows and n_A columns
# and B is a matrix with m_B rows and n_B columns

# Then dot product is only defined if m_A == n_B 
# so the shape of our new matrix C will be m_A rows and n_B columns
    C = np.zeros((A.shape[0],B.shape[1]))
    
    for i in range (0,A.shape[0]):
        for j in range (0, B.shape[1]):
            for n in range (0,B.shape[0]):
                C[i][j]= C[i][j] + (A[i][n]*B[n][j])
    
    return C

In [92]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([[2, 3], [5, 7], [11, 13]])

In [93]:
print(myDot(a,b))

[[ 45.  56.]
 [ 99. 125.]
 [153. 194.]
 [207. 263.]]


In [94]:
print(np.dot(a,b))

[[ 45  56]
 [ 99 125]
 [153 194]
 [207 263]]
