In [1]:
import numpy as np

In [4]:
v1 = np.array([1,2,3,4,5])

md = np.diag(v1)

print(md) #Square diagonal matrix

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [8]:
print(md[0:4,0:3]) #Non-square diagonal matrix

print(md[0:4,0:5])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [13]:
v2 = np.array([[1,1,1,1,1]])

print(md.dot(v2.T))

[[1]
 [2]
 [3]
 [4]
 [5]]


In [20]:
print(np.linalg.inv(md)) #Inverted diagonal matrix

print(md.dot(np.linalg.inv(md)))

[[ 1.          0.          0.          0.          0.        ]
 [ 0.          0.5         0.          0.          0.        ]
 [ 0.          0.          0.33333333  0.          0.        ]
 [-0.         -0.         -0.          0.25       -0.        ]
 [ 0.          0.          0.          0.          0.2       ]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
ms = np.array([[1,2,3], #Simetrical Matrix
               [2,4,5],
               [3,5,7]])

print(ms)
print(ms.T)

[[1 2 3]
 [2 4 5]
 [3 5 7]]
[[1 2 3]
 [2 4 5]
 [3 5 7]]
